### ISSUE TITLE
Whatever's done, getting 401 unauthorized whe requesting access

### ISSUE THREAD

**Issue by benbonnet** [jamiew/omniauth-tumblr#12]
Constantly getting a `OAuth::Unauthorized (401 Unauthorized)` before being redirected to tumblr to authorize the app

This gem always worked perfectly, checking out right here if something changed on tumblr side; or if the problem was obvious for anyone's reading

**Comment by jamiew** [comment]
Thanks for poking around. IIRC this gem is using an old version of their API, so maybe it's deprecated? Or down and not well monitored

**Comment by gonchs** [comment]
It's actually working, but only when the app url is set to http://localhost:3000. Setting a production url for the same app/keys results in 401 error.

**Comment by jamiew** [comment]
IIRC Tumblr requires separate keys for development vs. prod since you can
only have one allowed URL per auth token.

There's a brief mention about it in the omniauth-tumblr README:
https://github.com/jamiew/omniauth-tumblr

Does that sound like your issue?

**Comment by benbonnet** [comment]
Everything's okay. I really wonder why they care about the -dev redirecting to localhost
Maybe I had another old app with the same redirect urls. In the end I think it's on my side instead of the gem itself

**Comment by ghost** [comment]
Confirming it works. I didn't have a callback url set which for some reason worked on localhost but not in production.

**Comment by benbonnet** [comment]
Yep, I have a mess in my apps keys; that for some reasons causes troubles on tumblr to authorize. Currently sorting this out with their support
