### ISSUE TITLE
include spec directory in gem file itself

### ISSUE THREAD

**Issue by pravi** [jamiew/omniauth-tumblr#9]
this will be helpful of us packagers (I'm packaging for debian). Now we have to use github tarballs as source. Also please tag the releases so we don't have to give weird versions like 1.1+git.20140424.078c18c746 to identify the correct revision.

**Comment by jamiew** [comment]
I've tagged the `1.2` release 

On test/specs, but my understanding is that you shouldn't include them in gemfiles – e.g. https://github.com/mkdynamic/omniauth-facebook/blob/master/omniauth-facebook.gemspec – if you have a better example let me know and I'll reopen
